### ISSUE TITLE
Criar Suíte de Testes

### ISSUE THREAD

**Issue by ederign** [feroult/mycontainer-grid#1]
Verificar se não mistura os contextos
- http://partition1.grid/testapp/create - Cria msg
- http://partition1.grid/testapp/1 - Deve conter a msg
- http://partition2.grid/testapp/1- Não deve conter a msg

Paralelizar a execução dos testes com o testng

**Comment by ederign** [comment]
fiz os testes de paralelismo...

mvn test -Dparallel=classes -DthreadCount=n

Onde n ==  número de processadores da sua máquina, coloquei um thread.sleep lá pra sentir o ganho de performance com o paralelismo.

É estranho, mas creio que esta amarração se dê devido as instâncias novas do Firefox (processos). Ou talvez esteja tarde da noite eu esteja escrevendo merda! rs.

Talvez valha a pena testar em uma máquina top na amazon, mas aumentando a quantidade de testes.  Primeiro testa com uma thread, e depois com n.

Resultados na minha máquina: Core 2 Duo

mvn test -Dparallel=classes -DthreadCount=1

Total time: 50 seconds

mvn test -Dparallel=classes -DthreadCount=2

Total time: 35 seconds

mvn test -Dparallel=classes -DthreadCount=4

Total time: 33 seconds

**Comment by ederign** [comment]
Próximo passo agora é subir nas tasks do maven de pre-test o mycontainer, pra não ter que rodar o BootTests na mão! :)

**Comment by feroult** [comment]
@ederig precisamos definir como vai subir o mycontainer, se subirmos numa VM separada dos testes, vamos ter que fazer um esquema para comunicar aos containers como iremos fazer a limpeza de banco, etc. 

Você sabe se o FIREFOX está abrindo 2 processos ou 2 janelas do mesmo processo?

Poderíamos pensar em utilizar abas o mesmo FIREFOX para economizar no FIREFOX. Embora ache que ABAS tenha o mesmo efeito que duas janelas do mesmo processo.

Algumas referências que achei:

http://stackoverflow.com/questions/6032230/selenium-2-open-link-in-new-tab-and-close-tabs
http://stackoverflow.com/questions/6421988/webdriver-open-new-tab

**Comment by feroult** [comment]
O @marcospereirajr lembrou que com ABAS o Selenium vai reclamar de element no visible.

**Comment by ferciandt** [comment]
Lead time of 12 years! Congrats :P
